/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Santy
 */
import logica.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
public class Ventana extends javax.swing.JFrame implements ActionListener{
    Torre torre = new Torre();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }
    //Metodos
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JDialog();
        top = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_stat = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        menu = new javax.swing.JTabbedPane();
        tab_ingreso = new javax.swing.JPanel();
        pnl_ingreso = new javax.swing.JPanel();
        lbl_title_registro = new javax.swing.JLabel();
        sp_registro = new javax.swing.JSeparator();
        lbl_timEsp = new javax.swing.JLabel();
        lbl_placa1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_nparqueo_add = new javax.swing.JLabel();
        ipt_placa = new javax.swing.JTextField();
        ipt_hora = new javax.swing.JTextField();
        lbl_dosPuntos = new javax.swing.JLabel();
        ipt_min = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_tipo = new javax.swing.JList();
        lbl_tipo = new javax.swing.JLabel();
        lbl_horaentrada = new javax.swing.JLabel();
        lbl_hh = new javax.swing.JLabel();
        lbl_twoPoints = new javax.swing.JLabel();
        lbl_mm = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        ipt_id = new javax.swing.JTextField();
        lbl_status_add = new javax.swing.JLabel();
        tab_retirar = new javax.swing.JPanel();
        pnl_retirar = new javax.swing.JPanel();
        lbl_title_retiro = new javax.swing.JLabel();
        sp_retiro = new javax.swing.JSeparator();
        ipt_retiro = new javax.swing.JTextField();
        lbl_retiro = new javax.swing.JLabel();
        btn_retirar = new javax.swing.JButton();
        cbox_retiro = new javax.swing.JComboBox();
        lbl_status_ret = new javax.swing.JLabel();
        sp_retiro_bottom = new javax.swing.JSeparator();
        lbl_info_ret = new javax.swing.JLabel();
        btn_new_ret = new javax.swing.JButton();
        rigth = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_twoPoints1 = new javax.swing.JLabel();
        lbl_horas = new javax.swing.JLabel();
        lbl_minutos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_num_disp = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        lbl_sotano_size = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_plushh = new javax.swing.JButton();
        btn_plusmm = new javax.swing.JButton();
        btn_desalojar = new javax.swing.JButton();
        btn_reiniciar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_prox_placa = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_prox_hora = new javax.swing.JLabel();

        javax.swing.GroupLayout mensajeLayout = new javax.swing.GroupLayout(mensaje.getContentPane());
        mensaje.getContentPane().setLayout(mensajeLayout);
        mensajeLayout.setHorizontalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mensajeLayout.setVerticalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        top.setBackground(new java.awt.Color(35, 35, 35));

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(254, 233, 0));
        lbl_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title.setText("LE GRANDE CHOUQUE");

        lbl_stat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_stat.setForeground(new java.awt.Color(91, 165, 37));
        lbl_stat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_stat.setText("ACTIVO");

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(lbl_stat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_stat, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(35, 35, 35));

        menu.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        menu.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        tab_ingreso.setBackground(new java.awt.Color(255, 255, 255));

        pnl_ingreso.setBackground(new java.awt.Color(255, 255, 255));
        pnl_ingreso.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Registrar Veh\u00edculo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        lbl_title_registro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_title_registro.setForeground(new java.awt.Color(87, 87, 87));
        lbl_title_registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title_registro.setText("Nuevo Vehiculo");

        lbl_timEsp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_timEsp.setForeground(new java.awt.Color(0, 0, 0));
        lbl_timEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/watch.png"))); // NOI18N
        lbl_timEsp.setText("TIEMPO ESTADIA:");

        lbl_placa1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_placa1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_placa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car.png"))); // NOI18N
        lbl_placa1.setText("PLACA:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Numero Parqueo:");

        lbl_nparqueo_add.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbl_nparqueo_add.setText("#####");

        ipt_placa.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        ipt_placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipt_placa.setText("XXX###");
        ipt_placa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ipt_placa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipt_placaFocusGained(evt);
            }
        });

        ipt_hora.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ipt_hora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipt_hora.setText("HH");
        ipt_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_horaActionPerformed(evt);
            }
        });
        ipt_hora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipt_horaFocusGained(evt);
            }
        });

        lbl_dosPuntos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_dosPuntos.setText(":");

        ipt_min.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        ipt_min.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipt_min.setText("MM");
        ipt_min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_minActionPerformed(evt);
            }
        });
        ipt_min.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipt_minFocusGained(evt);
            }
        });

        list_tipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        list_tipo.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Automovil", "Campero", "Camioneta" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list_tipo.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(list_tipo);

        lbl_tipo.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vehicle.png"))); // NOI18N
        lbl_tipo.setText("TIPO VEHICULO:");

        lbl_horaentrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_horaentrada.setForeground(new java.awt.Color(0, 0, 0));
        lbl_horaentrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_horaentrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clock.png"))); // NOI18N
        lbl_horaentrada.setText("Hora Entrada:");

        lbl_hh.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_hh.setForeground(new java.awt.Color(87, 87, 87));
        lbl_hh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_hh.setText("HH");

        lbl_twoPoints.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_twoPoints.setText(":");

        lbl_mm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_mm.setForeground(new java.awt.Color(87, 87, 87));
        lbl_mm.setText("MM");

        btn_cancel.setBackground(new java.awt.Color(0, 0, 0));
        btn_cancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btn_cancel.setText("Cancelar");

        btn_new.setBackground(new java.awt.Color(0, 0, 0));
        btn_new.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_new.setForeground(new java.awt.Color(255, 255, 255));
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White_new.png"))); // NOI18N
        btn_new.setText("Nuevo");

        btn_save.setBackground(new java.awt.Color(244, 99, 80));
        btn_save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btn_save.setText("Guardar");
        btn_save.setBorder(null);

        lbl_id.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(0, 0, 0));
        lbl_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N
        lbl_id.setText("IDENTIFICACIÓN:");

        ipt_id.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        ipt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipt_id.setText("######");
        ipt_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ipt_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipt_idFocusGained(evt);
            }
        });

        lbl_status_add.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_status_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status_add.setText("");

        javax.swing.GroupLayout pnl_ingresoLayout = new javax.swing.GroupLayout(pnl_ingreso);
        pnl_ingreso.setLayout(pnl_ingresoLayout);
        pnl_ingresoLayout.setHorizontalGroup(
            pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_registro)
            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                                .addComponent(btn_cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_horaentrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ingresoLayout.createSequentialGroup()
                                        .addComponent(lbl_hh, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_twoPoints)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_mm, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20))))))
                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ipt_id)
                        .addGap(9, 9, 9))
                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                                .addComponent(ipt_placa)
                                .addGap(266, 266, 266))
                            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_nparqueo_add, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                                        .addComponent(lbl_placa1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_timEsp)))
                                .addGap(10, 10, 10)))))
                .addContainerGap())
            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ingresoLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(ipt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_dosPuntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipt_min, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbl_status_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_ingresoLayout.setVerticalGroup(
            pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ingresoLayout.createSequentialGroup()
                .addComponent(lbl_title_registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_nparqueo_add))
                .addGap(3, 3, 3)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_placa1)
                    .addComponent(lbl_timEsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipt_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_dosPuntos)
                    .addComponent(ipt_min, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tipo)
                    .addComponent(lbl_horaentrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_hh)
                        .addComponent(lbl_twoPoints)
                        .addComponent(lbl_mm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(ipt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_status_add, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_cancel.addActionListener(this);
        btn_cancel.setActionCommand("Cancelar");
        btn_new.addActionListener(this);
        btn_new.setActionCommand("Nuevo");
        btn_save.addActionListener(this);
        btn_save.setActionCommand("Guardar");

        javax.swing.GroupLayout tab_ingresoLayout = new javax.swing.GroupLayout(tab_ingreso);
        tab_ingreso.setLayout(tab_ingresoLayout);
        tab_ingresoLayout.setHorizontalGroup(
            tab_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_ingresoLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(pnl_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        tab_ingresoLayout.setVerticalGroup(
            tab_ingresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_ingresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        menu.addTab("Ingresar Vehiculo", tab_ingreso);

        tab_retirar.setBackground(new java.awt.Color(255, 255, 255));

        pnl_retirar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_retirar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Retirar Veh\u00edculo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        lbl_title_retiro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_title_retiro.setForeground(new java.awt.Color(87, 87, 87));
        lbl_title_retiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_title_retiro.setText("Retiro de Vehiculo");

        ipt_retiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipt_retiro.setText("######");
        ipt_retiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipt_retiroFocusGained(evt);
            }
        });

        lbl_retiro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_retiro.setText("Numero Parqueo:");

        btn_retirar.setText("Retirar");

        cbox_retiro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero de Parqueo", "Placa" }));

        lbl_status_ret.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_status_ret.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_status_ret.setText("");

        lbl_info_ret.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_info_ret.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_info_ret.setText("");
        lbl_info_ret.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btn_new_ret.setBackground(new java.awt.Color(0, 0, 0));
        btn_new_ret.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_new_ret.setForeground(new java.awt.Color(240, 240, 240));
        btn_new_ret.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White_new.png"))); // NOI18N
        btn_new_ret.setText("Nuevo");

        javax.swing.GroupLayout pnl_retirarLayout = new javax.swing.GroupLayout(pnl_retirar);
        pnl_retirar.setLayout(pnl_retirarLayout);
        pnl_retirarLayout.setHorizontalGroup(
            pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_retirarLayout.createSequentialGroup()
                .addGroup(pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_retirarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_retiro)
                            .addGroup(pnl_retirarLayout.createSequentialGroup()
                                .addComponent(lbl_title_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnl_retirarLayout.createSequentialGroup()
                                .addComponent(lbl_retiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ipt_retiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_status_ret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnl_retirarLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_info_ret, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_retirarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_new_ret, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)))
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_retirarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(sp_retiro_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnl_retirarLayout.setVerticalGroup(
            pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_retirarLayout.createSequentialGroup()
                .addComponent(lbl_title_retiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipt_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_retiro)
                    .addComponent(btn_retirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbox_retiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_status_ret)
                .addGap(18, 18, 18)
                .addComponent(lbl_info_ret, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_new_ret, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnl_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_retirarLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(sp_retiro_bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(451, Short.MAX_VALUE)))
        );

        btn_retirar.addActionListener(this);
        btn_retirar.setActionCommand("Retirar");
        btn_new_ret.addActionListener(this);
        btn_new_ret.setActionCommand("NuevoRetiro");

        javax.swing.GroupLayout tab_retirarLayout = new javax.swing.GroupLayout(tab_retirar);
        tab_retirar.setLayout(tab_retirarLayout);
        tab_retirarLayout.setHorizontalGroup(
            tab_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_retirarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab_retirarLayout.setVerticalGroup(
            tab_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_retirarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnl_retirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        menu.addTab("Retirar Vehiculo", tab_retirar);

        rigth.setBackground(new java.awt.Color(35, 35, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HORA");

        lbl_twoPoints1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_twoPoints1.setText(":");

        lbl_horas.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_horas.setForeground(new java.awt.Color(87, 87, 87));
        lbl_horas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_horas.setText(Integer.toString(torre.Clock().getHoraActual().getHora()));

        lbl_minutos.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_minutos.setForeground(new java.awt.Color(87, 87, 87));
        lbl_minutos.setText(Integer.toString(torre.Clock().getHoraActual().getMin()));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lugares");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Disponibles:");

        lbl_num_disp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_num_disp.setForeground(new java.awt.Color(51, 152, 219));
        lbl_num_disp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_num_disp.setText(Integer.toString(6340-torre.nVehiculos()));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("en Sotano:");

        jProgressBar1.setMaximum(6340);
        jProgressBar1.setValue(torre.nVehiculos());

        lbl_sotano_size.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_sotano_size.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sotano_size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_sotano_size.setText("00");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Adelantar:");

        btn_plushh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_plushh.setText(">");
        btn_plushh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plushhActionPerformed(evt);
            }
        });

        btn_plusmm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_plusmm.setText(">");
        btn_plusmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_plusmmActionPerformed(evt);
            }
        });

        btn_desalojar.setText("Desalojar");

        btn_reiniciar.setText("Reiniciar");
        btn_reiniciar.addActionListener(this);
        btn_reiniciar.setActionCommand("Reiniciar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 188, 156));
        jLabel6.setText("Proximo en Salir");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Placa:");

        lbl_prox_placa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_prox_placa.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prox_placa.setText(proxPlaca());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("a las:");

        lbl_prox_hora.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbl_prox_hora.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prox_hora.setText(proxHora());

        javax.swing.GroupLayout rigthLayout = new javax.swing.GroupLayout(rigth);
        rigth.setLayout(rigthLayout);
        rigthLayout.setHorizontalGroup(
            rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_num_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(rigthLayout.createSequentialGroup()
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rigthLayout.createSequentialGroup()
                        .addComponent(lbl_horas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_twoPoints1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rigthLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(rigthLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rigthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rigthLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_prox_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rigthLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rigthLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rigthLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(20, 20, 20))
                            .addGroup(rigthLayout.createSequentialGroup()
                                .addComponent(btn_plushh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_plusmm)
                                .addGap(15, 15, 15))))
                    .addGroup(rigthLayout.createSequentialGroup()
                        .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btn_reiniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_desalojar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(rigthLayout.createSequentialGroup()
                                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(rigthLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_sotano_size, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(rigthLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_prox_placa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        rigthLayout.setVerticalGroup(
            rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rigthLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_horas)
                    .addComponent(lbl_twoPoints1)
                    .addComponent(lbl_minutos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_plushh)
                    .addComponent(btn_plusmm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_num_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_sotano_size))
                .addGap(18, 18, 18)
                .addComponent(btn_desalojar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reiniciar)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_prox_placa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lbl_prox_hora))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_desalojar.addActionListener(this);
        btn_desalojar.setActionCommand("Desalojar");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(menu)
                .addGap(0, 0, 0)
                .addComponent(rigth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addComponent(rigth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ipt_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_horaActionPerformed

    private void ipt_minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_minActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_minActionPerformed

    private void ipt_placaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipt_placaFocusGained
        ipt_placa.selectAll();
    }//GEN-LAST:event_ipt_placaFocusGained

    private void ipt_horaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipt_horaFocusGained
        ipt_hora.selectAll();
    }//GEN-LAST:event_ipt_horaFocusGained

    private void ipt_minFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipt_minFocusGained
        ipt_min.selectAll();
    }//GEN-LAST:event_ipt_minFocusGained

    private void ipt_retiroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipt_retiroFocusGained
        ipt_retiro.selectAll();
    }//GEN-LAST:event_ipt_retiroFocusGained

    private void ipt_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipt_idFocusGained
        ipt_id.selectAll();
    }//GEN-LAST:event_ipt_idFocusGained

    private void btn_plushhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plushhActionPerformed
        torre.adelantarReloj(1,0);
        actualizar();
    }//GEN-LAST:event_btn_plushhActionPerformed

    private void btn_plusmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_plusmmActionPerformed
        torre.adelantarReloj(0,1);
        actualizar();
        
    }//GEN-LAST:event_btn_plusmmActionPerformed
    private void actualizar(){
        //Horas Panel Derecho
        lbl_horas.setText(Integer.toString(torre.Clock().getHoraActual().getHora()));
        lbl_minutos.setText(Integer.toString(torre.Clock().getHoraActual().getMin()));
        //Horas Registro
        lbl_hh.setText(Integer.toString(torre.Clock().getHoraActual().getHora()));
        lbl_mm.setText(Integer.toString(torre.Clock().getHoraActual().getMin()));
        //Luagres Disponibles
        lbl_num_disp.setText(Integer.toString(6340-torre.nVehiculos()));
        //Lugares en Sotano
        lbl_sotano_size.setText(Integer.toString(torre.inSotano()));
        //Proximo Vehiculo en Salir
        lbl_prox_placa.setText(proxPlaca());
        lbl_prox_hora.setText(proxHora());
        //estado
        if (torre.status()) {
            lbl_stat.setForeground(new java.awt.Color(91, 165, 37));
            lbl_stat.setText("ACTIVO");
        }
        else {
            lbl_stat.setForeground(new java.awt.Color(221,0,23));
            lbl_stat.setText("INACTIVO");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_desalojar;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_new_ret;
    private javax.swing.JButton btn_plushh;
    private javax.swing.JButton btn_plusmm;
    private javax.swing.JButton btn_reiniciar;
    private javax.swing.JButton btn_retirar;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox cbox_retiro;
    private javax.swing.JPanel content;
    private javax.swing.JTextField ipt_hora;
    private javax.swing.JTextField ipt_id;
    private javax.swing.JTextField ipt_min;
    private javax.swing.JTextField ipt_placa;
    private javax.swing.JTextField ipt_retiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_dosPuntos;
    private javax.swing.JLabel lbl_hh;
    private javax.swing.JLabel lbl_horaentrada;
    private javax.swing.JLabel lbl_horas;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_info_ret;
    private javax.swing.JLabel lbl_minutos;
    private javax.swing.JLabel lbl_mm;
    private javax.swing.JLabel lbl_nparqueo_add;
    private javax.swing.JLabel lbl_num_disp;
    private javax.swing.JLabel lbl_placa1;
    private javax.swing.JLabel lbl_prox_hora;
    private javax.swing.JLabel lbl_prox_placa;
    private javax.swing.JLabel lbl_retiro;
    private javax.swing.JLabel lbl_sotano_size;
    private javax.swing.JLabel lbl_stat;
    private javax.swing.JLabel lbl_status_add;
    private javax.swing.JLabel lbl_status_ret;
    private javax.swing.JLabel lbl_timEsp;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_title_registro;
    private javax.swing.JLabel lbl_title_retiro;
    private javax.swing.JLabel lbl_twoPoints;
    private javax.swing.JLabel lbl_twoPoints1;
    private javax.swing.JList list_tipo;
    private javax.swing.JDialog mensaje;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JPanel pnl_ingreso;
    private javax.swing.JPanel pnl_retirar;
    private javax.swing.JPanel rigth;
    private javax.swing.JSeparator sp_registro;
    private javax.swing.JSeparator sp_retiro;
    private javax.swing.JSeparator sp_retiro_bottom;
    private javax.swing.JPanel tab_ingreso;
    private javax.swing.JPanel tab_retirar;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String comando = e.getActionCommand();
        if(comando.equals("Guardar")){
            //lbl_title_registro.setText("Funciona!");
            if(isPlaca(ipt_placa.getText())&&isHH(ipt_hora.getText())&&
                    isMM(ipt_min.getText())&&list_tipo.getSelectedIndex()!=-1
                    &&isID(ipt_id.getText())&&torre.Clock().getHoraActual().
                    compararHora(new Hora(Integer.parseInt(ipt_hora.getText()),
                    Integer.parseInt(ipt_min.getText()))))
            {
                String tipo = "";
                switch(list_tipo.getSelectedIndex()){
                case 0:
                    tipo = "Automovil";
                    break;
                case 1:
                    tipo = "Campero";
                    break;
                case 2:
                    tipo = "Camioneta";
                    break;
                }
                int agregar = torre.agregar(ipt_placa.getText(), tipo, Integer.parseInt(ipt_hora.getText()), Integer.parseInt(ipt_min.getText()), Integer.parseInt(ipt_id.getText()));
                switch(agregar%10){
                    case 0:
                        lbl_status_add.setText("SIN ESPACIO");
                        lbl_status_add.setForeground(new Color(251,10,42));
                        if(agregar/10==0){
                            lbl_nparqueo_add.setText("No Entro");
                        }
                        else{
                        lbl_nparqueo_add.setText(Integer.toString(agregar/10));
                        }
                        break;
                    case 1:
                        lbl_status_add.setText("EN TORRE");
                        lbl_status_add.setForeground(new Color(59,89,152));
                        if(agregar/10==0){
                            lbl_nparqueo_add.setText("No Entro");
                        }
                        else{
                        lbl_nparqueo_add.setText(Integer.toString(agregar/10));
                        }
                        break;
                    case 2:
                        lbl_status_add.setText("EN SOTANO");
                        lbl_status_add.setForeground(new Color(91,165,37));
                        if(agregar/10==0){
                            lbl_nparqueo_add.setText("No Entro");
                        }
                        else{
                        lbl_nparqueo_add.setText(Integer.toString(agregar/10));
                        }
                        break;
                }
            }
            //Placa Mala
            else if(!isPlaca(ipt_placa.getText())){
                JOptionPane.showMessageDialog(mensaje,"Placa Incorrecta");                
            }
            //Hora Mala
            else if(!isHH(ipt_hora.getText())){
                JOptionPane.showMessageDialog(mensaje,"Hora De Salida Incorrecta");                
            }
            //Minutos Malos
            else if(!isMM(ipt_min.getText())){
                JOptionPane.showMessageDialog(mensaje,"Minutos De Salida Incorrectos");                
            }
            //No selecciona un tipo
            else if(list_tipo.getSelectedIndex()==-1){
                JOptionPane.showMessageDialog(mensaje,"Seleccione el Tipo de Vehiculo");                
            }
            //ID Malo
            else if(!isID(ipt_id.getText())){
                JOptionPane.showMessageDialog(mensaje,"Identificaci\u00f3n Incorracta");                
            }    
            //Hora Menor a Reloj
            else if(!torre.Clock().getHoraActual().compararHora(new Hora(Integer.parseInt(ipt_hora.getText()),
                    Integer.parseInt(ipt_min.getText())))){
                JOptionPane.showMessageDialog(mensaje,"Hora Incorrecta, Menor a la del Reloj");
            }
            actualizar();
        }
        else if(comando.equals("Nuevo")){
            ipt_placa.setText("");
            ipt_hora.setText("");
            ipt_min.setText("");
            list_tipo.removeSelectionInterval(0, 2);
            ipt_id.setText("");
            lbl_status_add.setText("");
            lbl_nparqueo_add.setText("");
        }
        else if(comando.equals("Cancelar")){
            ipt_placa.setText("XXX###");
            ipt_hora.setText("HH");
            ipt_min.setText("MM");
            list_tipo.removeSelectionInterval(0, 2);
            ipt_id.setText("########");
            lbl_status_add.setText("");
            lbl_nparqueo_add.setText("#####");
        }
        else if(comando.equals("Desalojar")){
            torre.desalojo();
            actualizar();
        }
        else if(comando.equals("Reiniciar")){
            torre.reiniciar();
            actualizar();
        }
        else if(comando.equals("Retirar")){
            //Saber Combo Box
            Object SaberSelec = cbox_retiro.getSelectedItem();
            //Selecciono nPArqueo
            if(String.valueOf(SaberSelec).equals("Numero de Parqueo")){
                if (isID(ipt_retiro.getText())) {
                    double cobro = 0.0;
                    int nivel = (Integer.parseInt(ipt_retiro.getText())%10000)/100; //Saber Nivel
                    int entrada = Integer.parseInt(ipt_retiro.getText())%100; //Saber Entrada
                    Hora horacobro;
                    if(torre.Clock().getHoraActual().getMin()>0){
                     horacobro = new Hora(torre.Clock().getHoraActual().getHora()+1,0);
                    }
                    else{
                     horacobro = torre.Clock().getHoraActual();
                    }
                    //Cobrar si se encuentra
                    if(torre.buscar(nivel, entrada, Integer.parseInt(ipt_retiro.getText()))!=null){
                        cobro = torre.cobro(torre.buscar(nivel, entrada, Integer.parseInt(ipt_retiro.getText())),horacobro);///torre.Clock().getHoraActual()
                    }
                    if (torre.retirar(Integer.parseInt(ipt_retiro.getText()))) {
                        lbl_status_ret.setText("Retirado");
                        lbl_info_ret.setText("<html>El Vehiculo del registro numero "+ipt_retiro.getText()+
                                "<P>Ha sido retirado exitosamente<P>"+
                                "<html>El Cobro total es de: "+cobro+"$<P>"
                                );
                    } 
                    else {
                        lbl_status_ret.setText("No Encontrado");
                    }
                }
                else {
                    lbl_status_ret.setText("Numero Incorrecto");
                }
            }
            //Selecciono Placa
            else if(String.valueOf(SaberSelec).equals("Placa")){
                if (isPlaca(ipt_retiro.getText())) {
                    double cobro = 0.0;
                    int nivel = (int)ipt_retiro.getText().charAt(0)-65; //Saber Nivel
                    int entrada = (int)ipt_retiro.getText().charAt(ipt_retiro.getText().length()-1)-48; //Saber Entrada
                    Hora horacobro;
                    if(torre.Clock().getHoraActual().getMin()>0){
                     horacobro = new Hora(torre.Clock().getHoraActual().getHora()+1,0);
                    }
                    else{
                     horacobro = torre.Clock().getHoraActual();
                    }
                    //Cobrar si se encuentra
                    if(torre.buscar(nivel, entrada, ipt_retiro.getText())!=null){
                        cobro = torre.cobro(torre.buscar(nivel, entrada,ipt_retiro.getText()), horacobro);//torre.Clock().getHoraActual()
                    }
                    Vehiculo temp = torre.buscar(nivel, entrada,ipt_retiro.getText());
                    if (torre.retirar(ipt_retiro.getText())) {
                        lbl_status_ret.setText("Retirado");
                        lbl_info_ret.setText("<html>El Vehiculo con placa "+ipt_retiro.getText()+" ha sido retirado exitosamente<P>"+
                                "<html>El Cobro total es de: "+cobro+"$<P>"
                                );
                    }
                    else {
                        lbl_status_ret.setText("No Encontrado");
                    }
                }
                else {
                    lbl_status_ret.setText("Placa Incorrecta");
                }
            }
            actualizar();
        }
        else if(comando.equals("NuevoRetiro")){
                ipt_retiro.setText("");
                lbl_status_ret.setText("");
                lbl_info_ret.setText("");
        }
    }
    
    public boolean isPlaca(String placa){
        boolean ret=true;

        //Saber si tiene 6 digitos
        if(placa.length()==6){
            //Si tiene 6 digitos
            //Saber si los 3 primeros son letras (Suponemos que estan en minusculas)
            for(int i=0;i<3;i++){
                //Si el caracter no es una Letra Mayuscula false
                if(((int)placa.charAt(i))<65||((int)placa.charAt(i))>90){
                    ret=false;
                }
            }
            //Saber si los 3 Ultimos son numeros
            try {
                Integer.parseInt(placa.substring(3,6));
            } catch (Exception e) {
                ret=false;
            }
        }
        else{
        ret = false;
        }
        return ret;
    }
    public boolean isID(String id){
        try {
            Integer.parseInt(id);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    public boolean isHH(String hh){
        boolean ret = true;
        try {
            int num = Integer.parseInt(hh);
            if(num<0||num>23){
                ret=false;
            }
        } catch (Exception e) {
            ret=false;
        }
        return ret;
    }
    public boolean isMM(String mm){
        boolean ret = true;
        try {
            int num = Integer.parseInt(mm);
            if(num<0||num>59){
                ret=false;
            }
        } catch (Exception e) {
            ret=false;
        }
        return ret;
    }
    public String proxHora(){
        String ret = "";
        if(torre.proxSalir()==null){
            ret = "HH:MM";
        }
        else{
            ret = torre.proxSalir().getHoraRetirada().getHora()+":"+torre.proxSalir().getHoraRetirada().getMin();
        }
        return ret;
    }
    public String proxPlaca(){
        String ret = "";
        if(torre.proxSalir()==null){
            ret = "XXX###";
        }
        else{
            ret = torre.proxSalir().getPlaca();
        }
        return ret;
    }

}
